"""Forest dashboard view."""

import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

from climate_dashboard.charts.theme import base
from climate_dashboard.components.navigation import go_to


def page_forest(forest):
    acc = "#4ade80"

    st.markdown(f"""
<div class="dash-wrap">
    <div class="dash-header" style="--bg-glow:rgba(74,222,128,0.17)">
        <div class="dash-header-glow"></div>
        <div class="dash-eyebrow" style="color:{acc}">
            <span class="dot" style="background:{acc}"></span>
            Biosphere · Ecosystem Collapse
        </div>
        <h1 class="dash-h1">Global <span style="color:{acc}">Deforestation</span></h1>
        <p class="dash-desc">
            Forests are the lungs of the Earth — they absorb CO₂, generate rainfall,
            shelter 80% of all land species, and sustain 1.6 billion people's livelihoods.
            We are destroying them at a rate of roughly <strong style="color:#4ade80">one football pitch every second</strong>.
            Once gone, they take decades to regenerate — and the species lost never return.
        </p>
    </div>
</div>""", unsafe_allow_html=True)

    if st.button("← Back to Home", key="back_forest"):
        go_to("home")

    total_loss   = forest["forest_loss"].sum()
    peak_yr_loss = forest.groupby("year")["forest_loss"].sum().max()
    worst_yr     = int(forest.groupby("year")["forest_loss"].sum().idxmax())
    top_country  = forest.groupby("country")["forest_loss"].sum().idxmax()
    co2_equiv_gt = total_loss * 200_000 / 1e12

    kpi_data = [
        ("Total Forest Destroyed",   f"{total_loss:,.0f} km²",   "Cumulative across all countries",           "rise"),
        ("Peak Annual Loss",          f"{peak_yr_loss:,.0f} km²", f"Worst single year: {worst_yr}",             "rise"),
        ("CO₂ Released (Estimate)",   f"{co2_equiv_gt:.1f} Gt",   "≈200,000 t CO₂ per km² of forest",          "rise"),
        ("Worst Offender All-Time",   top_country,                 "By cumulative total forest destroyed",       "neutral"),
    ]
    st.markdown('<div class="kstrip">', unsafe_allow_html=True)
    kpi_cols = st.columns(4)
    for col, (lbl, val, delta, cls) in zip(kpi_cols, kpi_data):
        with col:
            st.markdown(f"""
<div class="kcard" style="--cc:{acc}">
    <div class="kcard-lbl">{lbl}</div>
    <div class="kcard-val">{val}</div>
    <div class="kcard-delta {cls}">{delta}</div>
</div>""", unsafe_allow_html=True)
    st.markdown("</div>", unsafe_allow_html=True)

    st.markdown('<div class="chart-area">', unsafe_allow_html=True)

    # ── Forest Clock ──
    yrs_of_data = max(1, int(forest["year"].max() - forest["year"].min()))
    avg_annual  = total_loss / yrs_of_data
    per_hour    = avg_annual / 8760
    per_second  = avg_annual / (365 * 24 * 3600)
    st.markdown(f"""
<div class="forest-clock">
    <div class="fc-icon">🌍</div>
    <div class="fc-text">
        <div class="fc-title">The Deforestation Clock — It Never Stops</div>
        <div class="fc-body">
            Based on this dataset, an estimated <strong>{avg_annual:,.0f} km²</strong> of forest is cleared every year.
            That is <strong>{per_hour:.2f} km²</strong> every hour, or roughly
            <strong>{per_second:.4f} km²</strong> every second — continuously, day and night.
            Tropical forests take 30–100 years to recover even with active replanting.
            The biodiversity, carbon storage, and rainfall generation are never fully restored.
        </div>
    </div>
    <div>
        <div class="fc-stat">{per_hour:.1f}</div>
        <div class="fc-stat-sub">km² per hour</div>
    </div>
</div>""", unsafe_allow_html=True)

    # ── Why forests matter ──
    st.markdown("""
<div class="eyebrow" style="padding:0 0 10px">🌿 Why Forests Are Irreplaceable</div>
<div class="forest-why">
    <div class="fw-card">
        <span class="fw-icon">🐘</span>
        <div class="fw-stat">80%</div>
        <div class="fw-label">of Earth's land species</div>
        <div class="fw-text">Live in forests. Destroying a forest eliminates the only home countless species have ever known — many before we even discover them. Extinction is permanent.</div>
    </div>
    <div class="fw-card">
        <span class="fw-icon">💧</span>
        <div class="fw-stat">20%</div>
        <div class="fw-label">of global rainfall</div>
        <div class="fw-text">Generated by the Amazon alone through transpiration. Deforestation creates droughts that extend far beyond the forest's own boundaries — affecting farms and cities hundreds of miles away.</div>
    </div>
    <div class="fw-card">
        <span class="fw-icon">💊</span>
        <div class="fw-stat">25%</div>
        <div class="fw-label">of medicines</div>
        <div class="fw-text">Originated from rainforest plants. We are burning pharmacies before cataloguing their contents — each species lost may be a cure never found for cancer, Alzheimer's, or the next pandemic.</div>
    </div>
    <div class="fw-card">
        <span class="fw-icon">🌡️</span>
        <div class="fw-stat">2.6 Gt</div>
        <div class="fw-label">CO₂ absorbed/year</div>
        <div class="fw-text">By tropical forests alone. Each km² destroyed both releases stored carbon and permanently removes that annual absorption capacity — a double blow to the climate system.</div>
    </div>
</div>""", unsafe_allow_html=True)

    # ── Species at risk visual ──
    st.markdown("""
<div class="eyebrow" style="padding:8px 0 10px">🦋 Species Threatened by Deforestation</div>
<div class="species-grid">
    <div class="species-tile">🦁 1,000+ large mammal populations lost</div>
    <div class="species-tile">🦜 75% of parrot species threatened</div>
    <div class="species-tile">🐸 40% of amphibians at extinction risk</div>
    <div class="species-tile">🦋 30% of insect species in decline</div>
    <div class="species-tile">🐆 Jaguar lost 46% of Amazon range</div>
    <div class="species-tile">🦧 Orangutan 80% habitat destroyed</div>
    <div class="species-tile">🐘 Forest elephant population halved</div>
    <div class="species-tile">🐍 Reptile diversity drops 50% in cleared areas</div>
</div>""", unsafe_allow_html=True)

    # ── Animated bar race ──
    forest_s = forest.sort_values(["year","forest_loss"], ascending=[True,True])
    fig_race = px.bar(
        forest_s, x="forest_loss", y="country",
        animation_frame="year", orientation="h",
        color="forest_loss",
        color_continuous_scale=[[0,"#14532d"],[0.35,"#166534"],[0.65,"#4ade80"],[1,"#bbf7d0"]],
        labels={"forest_loss":"km² Lost","country":""},
    )
    fig_race.update_traces(texttemplate="%{x:.0f} km²", textposition="outside", textfont=dict(color="#86efac", size=11))
    fig_race.update_layout(**base(title="Deforestation Race — Country Rankings Year by Year"), xaxis_title="Forest Loss (km²)", yaxis_title="", coloraxis_showscale=False)
    st.markdown("""
<div class="ccard" style="--cc:#4ade80">
    <div class="ccard-title">🎬 The Deforestation Race — Press ▶ to Animate</div>
    <div class="ccard-sub">Each bar = one country's forest loss that year · Press ▶ to watch country rankings shift over time · Longer bar = more forest destroyed in that year</div>
    <div class="ccard-explain">💡 Watch for sudden surges in a country's bar — these coincide with policy changes, new agricultural expansion, or infrastructure projects. Brazil's Amazon is visible as the dominant driver, but the pattern shifts as other nations accelerate their own clearing.</div>
</div>""", unsafe_allow_html=True)
    st.plotly_chart(fig_race, use_container_width=True, key="forest_race")

    col_a, col_b = st.columns(2)

    with col_a:
        global_loss = forest.groupby("year")["forest_loss"].sum().reset_index()
        fig_loss = go.Figure()
        fig_loss.add_trace(go.Scatter(
            x=global_loss["year"], y=global_loss["forest_loss"],
            mode="none", fill="tozeroy", fillcolor="rgba(74,222,128,0.08)", showlegend=False, hoverinfo="skip",
        ))
        fig_loss.add_trace(go.Scatter(
            x=global_loss["year"], y=global_loss["forest_loss"], mode="lines+markers",
            marker=dict(size=7, color=acc, line=dict(color="#14532d", width=1.5)),
            line=dict(color=acc, width=3, shape="spline"), name="Global Total",
            hovertemplate="<b>%{x}</b><br>Total Loss: %{y:,.0f} km²<extra></extra>",
        ))
        fig_loss.add_trace(go.Scatter(
            x=global_loss["year"], y=global_loss["forest_loss"].rolling(3, center=True).mean(),
            mode="lines", line=dict(color="#a3e635", width=1.8, dash="dot"), name="3-yr Trend",
        ))
        fig_loss.update_layout(**base(title="Global Forest Loss Per Year — All Countries Combined"), xaxis_title="Year", yaxis_title="km² of forest destroyed")
        st.markdown("""
<div class="ccard" style="--cc:#4ade80">
    <div class="ccard-title">📉 How Much Forest Is Lost Each Year Globally?</div>
    <div class="ccard-sub">Total annual deforestation across all tracked countries · Dotted line = 3-year smoothed trend · Higher = more forests destroyed that year · Each km² = over 100 football pitches</div>
    <div class="ccard-explain">💡 Each km² on this chart represents an area larger than 100 football pitches — gone permanently in a single year. The dotted trend line shows whether the overall rate of destruction is rising, falling, or stabilising.</div>
</div>""", unsafe_allow_html=True)
        st.plotly_chart(fig_loss, use_container_width=True, key="forest_trend")

    with col_b:
        global_loss["co2_released_mt"] = global_loss["forest_loss"] * 200_000 / 1e6
        fig_co2 = go.Figure()
        fig_co2.add_trace(go.Bar(
            x=global_loss["year"], y=global_loss["co2_released_mt"],
            marker=dict(color=global_loss["co2_released_mt"], colorscale=[[0,"#14532d"],[0.5,"#16a34a"],[1,"#86efac"]], line=dict(width=0)),
            hovertemplate="<b>%{x}</b><br>CO₂ Released: ~%{y:,.0f} Mt<extra></extra>", name="CO₂ Equivalent",
        ))
        fig_co2.update_layout(**base(title="Carbon Released by Deforestation (Estimated)"), xaxis_title="Year", yaxis_title="Million tonnes CO₂ (estimated)")
        st.markdown("""
<div class="ccard" style="--cc:#4ade80">
    <div class="ccard-title">💨 How Much Carbon Does Deforestation Release Each Year?</div>
    <div class="ccard-sub">Estimated CO₂ released from forest destruction · Using ~200,000 tonnes CO₂ per km² of tropical forest — a standard scientific benchmark used by the IPCC</div>
    <div class="ccard-explain">💡 Deforestation accounts for roughly <strong>10–15% of global CO₂ emissions</strong> — comparable to the entire global transportation sector. Stopping deforestation would be one of the single most effective and cheapest climate actions available today.</div>
</div>""", unsafe_allow_html=True)
        st.plotly_chart(fig_co2, use_container_width=True, key="forest_co2eq")

    col_c, col_d = st.columns(2)

    with col_c:
        top10_f = (
            forest.groupby("country")["forest_loss"]
            .sum().nlargest(10).reset_index().sort_values("forest_loss")
        )
        fig_top = go.Figure(go.Bar(
            x=top10_f["forest_loss"], y=top10_f["country"], orientation="h",
            marker=dict(color=top10_f["forest_loss"], colorscale=[[0,"#14532d"],[0.5,"#16a34a"],[1,"#4ade80"]], line=dict(width=0)),
            text=top10_f["forest_loss"].apply(lambda v: f"{v:,.0f}"),
            textposition="outside", textfont=dict(color="#86efac", size=11),
            hovertemplate="<b>%{y}</b><br>Total Loss: %{x:,.0f} km²<extra></extra>",
        ))
        fig_top.update_layout(**base(title="Countries That Destroyed the Most Forest"), xaxis_title="Total forest destroyed (km²)", yaxis_title="", bargap=0.24)
        st.markdown("""
<div class="ccard" style="--cc:#4ade80">
    <div class="ccard-title">🏆 Worst Deforesters — Cumulative All-Time Total</div>
    <div class="ccard-sub">Total forest destroyed by each country across the full dataset · Longer bar = more cumulative forest lost · This is the historical responsibility ledger</div>
    <div class="ccard-explain">💡 Brazil's dominance reflects the Amazon — the world's largest tropical forest and most important carbon sink. Indonesia reflects rapid palm oil-driven clearing of Borneo and Sumatra's irreplaceable rainforests.</div>
</div>""", unsafe_allow_html=True)
        st.plotly_chart(fig_top, use_container_width=True, key="forest_top10")

    with col_d:
        top5_f = forest.groupby("country")["forest_loss"].sum().nlargest(5).index.tolist()
        GREEN5 = ["#4ade80","#a3e635","#22c55e","#86efac","#16a34a"]
        fig_lines = go.Figure()
        for country, clr in zip(top5_f, GREEN5):
            df_c = forest[forest["country"] == country].sort_values("year")
            fig_lines.add_trace(go.Scatter(
                x=df_c["year"], y=df_c["forest_loss"], mode="lines+markers",
                marker=dict(size=6, color=clr, line=dict(color="#14532d", width=1)),
                line=dict(color=clr, width=2.5, shape="spline"), name=country,
                hovertemplate=f"<b>{country}</b> %{{x}}: %{{y:,.0f}} km²<extra></extra>",
            ))
        fig_lines.update_layout(**base(title="Top 5 Countries — Year-by-Year Deforestation"), xaxis_title="Year", yaxis_title="Forest loss that year (km²)")
        st.markdown("""
<div class="ccard" style="--cc:#4ade80">
    <div class="ccard-title">📊 How Have Individual Countries' Deforestation Changed Over Time?</div>
    <div class="ccard-sub">Each line tracks one country's annual forest loss · Lines dropping = policies are working · Lines spiking = destruction is accelerating · Hover for exact values</div>
    <div class="ccard-explain">💡 Lines that drop often coincide with specific policies — Brazil's Amazon Soy Moratorium is visible as a period of reduction. When political will weakened, the line surged back up. <strong>Policy works.</strong> The question is whether governments commit to it.</div>
</div>""", unsafe_allow_html=True)
        st.plotly_chart(fig_lines, use_container_width=True, key="forest_lines")

    # Proportional share donut
    country_totals = forest.groupby("country")["forest_loss"].sum().reset_index().sort_values("forest_loss", ascending=False)
    fig_pie = go.Figure(go.Pie(
        labels=country_totals["country"],
        values=country_totals["forest_loss"],
        hole=0.58,
        marker=dict(colors=["#4ade80","#a3e635","#22c55e","#86efac","#16a34a","#166534","#14532d","#365314","#1a2e05","#84cc16"]),
        textfont=dict(size=13, color="#f0fdf4"),
        hovertemplate="<b>%{label}</b><br>%{value:,.0f} km²<br>%{percent}<extra></extra>",
    ))
    fig_pie.update_layout(**base(title="Share of Total Deforestation by Country"), legend=dict(font=dict(size=13, color="#86efac")))
    st.markdown("""
<div class="ccard" style="--cc:#4ade80">
    <div class="ccard-title">🌿 Which Country Bears the Most Responsibility?</div>
    <div class="ccard-sub">Proportional breakdown of total deforestation across all countries · Hover each slice for the exact figure and percentage share · A small number of countries dominate</div>
    <div class="ccard-explain">💡 This concentration of responsibility means that targeted international pressure, financial incentives, and governance reforms in just 3–5 nations could dramatically reduce the <em>global</em> rate of deforestation. The leverage is enormous.</div>
</div>""", unsafe_allow_html=True)
    st.plotly_chart(fig_pie, use_container_width=True, key="forest_pie")

    st.markdown(f"""
<div class="callout">
    <strong>🌱 What recovery would actually take:</strong> At the current rate,
    an estimated <strong>{avg_annual:,.0f} km² of forest is cleared every year.</strong>
    Tropical forests take 30–100 years to fully recover even with active replanting.
    Even if all deforestation stopped today, restoring the roughly
    <strong>{total_loss:,.0f} km²</strong> lost over this dataset period would take generations.
    Prevention is exponentially cheaper, faster, and more effective than restoration — every year of inaction compounds the debt.
</div>""", unsafe_allow_html=True)

    st.markdown("</div>", unsafe_allow_html=True)
